# Generated by Django 4.1.7 on 2023-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_brought', models.CharField(max_length=255)),
                ('item_brand', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('date_brought', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('date_issued', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_brand', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('date_dispensed', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inkind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('date_supplied', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('date_of_creation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_bought', models.CharField(max_length=255)),
                ('item_price', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('date_bought', models.CharField(max_length=255)),
            ],
        ),
    ]
